GENESIS_TIME: 1770941151
GENESIS_VALIDATORS:
  - "0x2ad5f755ea8c7b4016279a0b091ee115f31c9c47d7230221759580223d24ca7357b41313695158180c10f2047dc70b1cc9e30165"
  - "0xd0b7d84f6591823e030d82562f657015a2ce1a41fb8b982900d0ed6347b7687dca6eb56bd51028436af24e63a27f6c287add6a21"
  - "0x7a460c1a621a8d60495d405a6437fb5bcc772338873ba91299a9612ca88bd071db552a6d10e2446cbc9a380c751f562e856f6855"
  - "0xb834bb5bc1ff412be17a6f423442062279eca4394145a511c0df8b6cc1174471129b8318d0732a6ec2d112775791f67a54cd4110"
  - "0x56df7859f287c02de99211008c8c992ea5540250649b0614a2b4846f409c6a3c6fde7207f202f0217a3dc910dac0b86a61d04459"

